Lint/ShadowingOuterLocalVar:
  Description: Disallows the usage of the same name as outer local variables for block
    or proc arguments.
  Excluded:
  - src/retrieve_token.cr
  Enabled: true
  Severity: Warning
