version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    network_mode: host

  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      VERSION: 1.18.2
      ONLINE_MODE: "FALSE"
      MAX_WORLD_SIZE: 10
      LEVEL_TYPE: flat
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - ../spec/fixtures/server:/data
