services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      VERSION: 1.21
      ONLINE_MODE: "FALSE"
      LEVEL_TYPE: flat

    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - ./fixtures/server:/data