name: Deploy docs

on:
  push:
    branches: [main]
  pull_request:

jobs:
  deploy:
    if: github.repository != 'grepsedawk/sharded.cr'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - uses: crystal-lang/install-crystal@v1
      - name: "Install shards"
        run: shards install --without-development
      - name: "Generate docs"
        run: crystal docs
      - name: Deploy to GitHub Pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
